# Generated by Django 5.2.9 on 2025-12-17 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "expense",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "income",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
